<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->delete();
        // Call The Defined Factory From UserFactory
        // factory(App\Country::class, 13)->create();
        $countries = [
            ['code' => 'US', 'english_name' => 'United States', 'arabic_name' => 'الولايات المتحدة', 'slug' => 'الولايات-المتحدة'],
            ['code' => 'CA', 'english_name' => 'Canada', 'arabic_name' => 'كندا', 'slug' => 'كندا'],
            ['code' => 'AF', 'english_name' => 'Afghanistan', 'arabic_name' => 'أفغانستان', 'slug' => 'أفغانستان'],
            ['code' => 'AL', 'english_name' => 'Albania', 'arabic_name' => 'ألبانيا', 'slug' => 'ألبانيا'],
            ['code' => 'DZ', 'english_name' => 'Algeria', 'arabic_name' => 'الجزائر', 'slug' => 'الجزائر'],
            ['code' => 'AS', 'english_name' => 'American Samoa', 'arabic_name' => 'ساموا الأمريكية', 'slug' => 'ساموا-الأمريكية'],
            ['code' => 'AD', 'english_name' => 'Andorra', 'arabic_name' => 'أندورا', 'slug' => 'أندورا'],
            ['code' => 'AO', 'english_name' => 'Angola', 'arabic_name' => 'أنغولا', 'slug' => 'أنغولا'],
            ['code' => 'AI', 'english_name' => 'Anguilla', 'arabic_name' => 'أنغويلا', 'slug' => 'أنغويلا'],
            ['code' => 'AQ', 'english_name' => 'Antarctica', 'arabic_name' => 'أنتاركتيكا', 'slug' => 'أنتاركتيكا'],
            ['code' => 'AG', 'english_name' => 'Antigua and/or Barbuda', 'arabic_name' => 'أنتيغوا وبربودا', 'slug' => 'أنتيغوا-وبربودا'],
            ['code' => 'AR', 'english_name' => 'Argentina', 'arabic_name' => 'الأرجنتين', 'slug' => 'الأرجنتين'],
            ['code' => 'AM', 'english_name' => 'Armenia', 'arabic_name' => 'أرمينيا', 'slug' => 'أرمينيا'],
            ['code' => 'AW', 'english_name' => 'Aruba', 'arabic_name' => 'أروبا', 'slug' => 'أروبا'],
            ['code' => 'AU', 'english_name' => 'Australia', 'arabic_name' => 'أستراليا', 'slug' => 'أستراليا'],
            ['code' => 'AT', 'english_name' => 'Austria', 'arabic_name' => 'النمسا', 'slug' => 'النمسا'],
            ['code' => 'AZ', 'english_name' => 'Azerbaijan', 'arabic_name' => 'أذربيجان', 'slug' => 'أذربيجان'],
            ['code' => 'BS', 'english_name' => 'Bahamas', 'arabic_name' => 'البهاما', 'slug' => 'البهاما'],
            ['code' => 'BH', 'english_name' => 'Bahrain', 'arabic_name' => 'البحرين', 'slug' => 'البحرين'],
            ['code' => 'BD', 'english_name' => 'Bangladesh', 'arabic_name' => 'بنغلاديش', 'slug' => 'بنغلاديش'],
            ['code' => 'BB', 'english_name' => 'Barbados', 'arabic_name' => 'بربادوس', 'slug' => 'بربادوس'],
            ['code' => 'BY', 'english_name' => 'Belarus', 'arabic_name' => 'بيلاروس', 'slug' => 'بيلاروس'],
            ['code' => 'BE', 'english_name' => 'Belgium', 'arabic_name' => 'بلجيكا', 'slug' => 'بلجيكا'],
            ['code' => 'BZ', 'english_name' => 'Belize', 'arabic_name' => 'بليز', 'slug' => 'بليز'],
            ['code' => 'BJ', 'english_name' => 'Benin', 'arabic_name' => 'بنين', 'slug' => 'بنين'],
            ['code' => 'BM', 'english_name' => 'Bermuda', 'arabic_name' => 'برمودا', 'slug' => 'برمودا'],
            ['code' => 'BT', 'english_name' => 'Bhutan', 'arabic_name' => 'بوتان', 'slug' => 'بوتان'],
            ['code' => 'BO', 'english_name' => 'Bolivia', 'arabic_name' => 'بوليفيا', 'slug' => 'بوليفيا'],
            ['code' => 'BA', 'english_name' => 'Bosnia and Herzegovina', 'arabic_name' => 'البوسنة والهرسك', 'slug' => 'البوسنة-والهرسك'],
            ['code' => 'BW', 'english_name' => 'Botswana', 'arabic_name' => 'بتسوانا', 'slug' => 'بتسوانا'],
            ['code' => 'BV', 'english_name' => 'Bouvet Island', 'arabic_name' => 'جزيرة بوفيت', 'slug' => 'جزيرة-بوفيت'],
            ['code' => 'BR', 'english_name' => 'Brazil', 'arabic_name' => 'البرازيل', 'slug' => 'البرازيل'],
            ['code' => 'IO', 'english_name' => 'British lndian Ocean Territory', 'arabic_name' => 'الإقليم البريطاني في المحيط الهندي', 'slug' => 'الإقليم-البريطاني-في-المحيط-الهندي'],
            ['code' => 'BN', 'english_name' => 'Brunei Darussalam', 'arabic_name' => 'بروناي', 'slug' => 'بروناي'],
            ['code' => 'BG', 'english_name' => 'Bulgaria', 'arabic_name' => 'بلغاريا', 'slug' => 'بلغاريا'],
            ['code' => 'BF', 'english_name' => 'Burkina Faso', 'arabic_name' => 'بوركينا فاسو', 'slug' => 'بوركينا-فاسو'],
            ['code' => 'BI', 'english_name' => 'Burundi', 'arabic_name' => 'بوروندي', 'slug' => 'بوروندي'],
            ['code' => 'KH', 'english_name' => 'Cambodia', 'arabic_name' => 'كمبوديا', 'slug' => 'كمبوديا'],
            ['code' => 'CM', 'english_name' => 'Cameroon', 'arabic_name' => 'الكاميرون', 'slug' => 'الكاميرون'],
            ['code' => 'CV', 'english_name' => 'Cape Verde', 'arabic_name' => 'الرأس الأخضر', 'slug' => 'الرأس-الأخضر'],
            ['code' => 'KY', 'english_name' => 'Cayman Islands', 'arabic_name' => 'جزر كايمان', 'slug' => 'جزر-كايمان'],
            ['code' => 'CF', 'english_name' => 'Central African Republic', 'arabic_name' => 'جمهورية أفريقيا الوسطى', 'slug' => 'جمهورية-أفريقيا-الوسطى'],
            ['code' => 'TD', 'english_name' => 'Chad', 'arabic_name' => 'تشاد', 'slug' => 'تشاد'],
            ['code' => 'CL', 'english_name' => 'Chile', 'arabic_name' => 'تشيلي', 'slug' => 'تشيلي'],
            ['code' => 'CN', 'english_name' => 'China', 'arabic_name' => 'الصين', 'slug' => 'الصين'],
            ['code' => 'CX', 'english_name' => 'Christmas Island', 'arabic_name' => 'جزيرة الكريسماس', 'slug' => 'جزيرة-الكريسماس'],
            ['code' => 'CC', 'english_name' => 'Cocos (Keeling) Islands', 'arabic_name' => 'جزر كوكوس (كيلينغ)', 'slug' => 'جزر-كوكوس-كيلينغ'],
            ['code' => 'CO', 'english_name' => 'Colombia', 'arabic_name' => 'كولومبيا', 'slug' => 'كولومبيا'],
            ['code' => 'KM', 'english_name' => 'Comoros', 'arabic_name' => 'جزر القمر', 'slug' => 'جزر-القمر'],
            ['code' => 'CG', 'english_name' => 'Congo', 'arabic_name' => 'الكونغو - برازافيل', 'slug' => 'الكونغو-برازافيل'],
            ['code' => 'CK', 'english_name' => 'Cook Islands', 'arabic_name' => 'جزر كوك', 'slug' => 'جزر-كوك'],
            ['code' => 'CR', 'english_name' => 'Costa Rica', 'arabic_name' => 'كوستاريكا', 'slug' => 'كوستاريكا'],
            ['code' => 'HR', 'english_name' => 'Croatia (Hrvatska)', 'arabic_name' => 'كرواتيا', 'slug' => 'كرواتيا'],
            ['code' => 'CU', 'english_name' => 'Cuba', 'arabic_name' => 'كوبا', 'slug' => 'كوبا'],
            ['code' => 'CY', 'english_name' => 'Cyprus', 'arabic_name' => 'قبرص', 'slug' => 'قبرص'],
            ['code' => 'CZ', 'english_name' => 'Czech Republic', 'arabic_name' => 'التشيك', 'slug' => 'التشيك'],
            ['code' => 'CD', 'english_name' => 'Democratic Republic of Congo', 'arabic_name' => 'الكونغو - كينشاسا', 'slug' => 'الكونغو-كينشاسا'],
            ['code' => 'DK', 'english_name' => 'Denmark', 'arabic_name' => 'الدانمرك', 'slug' => 'الدانمرك'],
            ['code' => 'DJ', 'english_name' => 'Djibouti', 'arabic_name' => 'جيبوتي', 'slug' => 'جيبوتي'],
            ['code' => 'DM', 'english_name' => 'Dominica', 'arabic_name' => 'دومينيكا', 'slug' => 'دومينيكا'],
            ['code' => 'DO', 'english_name' => 'Dominican Republic', 'arabic_name' => 'جمهورية الدومينيكان', 'slug' => 'جمهورية-الدومينيكان'],
            ['code' => 'TP', 'english_name' => 'East Timor', 'arabic_name' => 'تيمور الشرقية', 'slug' => 'تيمور-الشرقية'],
            ['code' => 'EC', 'english_name' => 'Ecudaor', 'arabic_name' => 'الإكوادور', 'slug' => 'الإكوادور'],
            ['code' => 'EG', 'english_name' => 'Egypt', 'arabic_name' => 'مصر', 'slug' => 'مصر'],
            ['code' => 'SV', 'english_name' => 'El Salvador', 'arabic_name' => 'السلفادور', 'slug' => 'السلفادور'],
            ['code' => 'GQ', 'english_name' => 'Equatorial Guinea', 'arabic_name' => 'غينيا الاستوائية', 'slug' => 'غينيا-الاستوائية'],
            ['code' => 'ER', 'english_name' => 'Eritrea', 'arabic_name' => 'إريتريا', 'slug' => 'إريتريا'],
            ['code' => 'EE', 'english_name' => 'Estonia', 'arabic_name' => 'إستونيا', 'slug' => 'إستونيا'],
            ['code' => 'ET', 'english_name' => 'Ethiopia', 'arabic_name' => 'إثيوبيا', 'slug' => 'إثيوبيا'],
            ['code' => 'FK', 'english_name' => 'Falkland Islands (Malvinas)', 'arabic_name' => 'جزر فوكلاند', 'slug' => 'جزر-فوكلاند'],
            ['code' => 'FO', 'english_name' => 'Faroe Islands', 'arabic_name' => 'جزر فارو', 'slug' => 'جزر-فارو'],
            ['code' => 'FJ', 'english_name' => 'Fiji', 'arabic_name' => 'فيجي', 'slug' => 'فيجي'],
            ['code' => 'FI', 'english_name' => 'Finland', 'arabic_name' => 'فنلندا', 'slug' => 'فنلندا'],
            ['code' => 'FR', 'english_name' => 'France', 'arabic_name' => 'فرنسا', 'slug' => 'فرنسا'],
            ['code' => 'FX', 'english_name' => 'France, Metropolitan', 'arabic_name' => 'فرنسا ، متروبوليتان', 'slug' => 'فرنسا-متروبوليتان'],
            ['code' => 'GF', 'english_name' => 'French Guiana', 'arabic_name' => 'غويانا الفرنسية', 'slug' => 'غويانا-الفرنسية'],
            ['code' => 'PF', 'english_name' => 'French Polynesia', 'arabic_name' => 'بولينيزيا الفرنسية', 'slug' => 'بولينيزيا-الفرنسية'],
            ['code' => 'TF', 'english_name' => 'French Southern Territories', 'arabic_name' => 'الأقاليم الجنوبية الفرنسية', 'slug' => 'الأقاليم-الجنوبية-الفرنسية'],
            ['code' => 'GA', 'english_name' => 'Gabon', 'arabic_name' => 'الغابون', 'slug' => 'الغابون'],
            ['code' => 'GM', 'english_name' => 'Gambia', 'arabic_name' => 'غامبيا', 'slug' => 'غامبيا'],
            ['code' => 'GE', 'english_name' => 'Georgia', 'arabic_name' => 'جورجيا', 'slug' => 'جورجيا'],
            ['code' => 'DE', 'english_name' => 'Germany', 'arabic_name' => 'ألمانيا', 'slug' => 'ألمانيا'],
            ['code' => 'GH', 'english_name' => 'Ghana', 'arabic_name' => 'غانا', 'slug' => 'غانا'],
            ['code' => 'GI', 'english_name' => 'Gibraltar', 'arabic_name' => 'جبل طارق', 'slug' => 'جبل طارق'],
            ['code' => 'GR', 'english_name' => 'Greece', 'arabic_name' => 'اليونان', 'slug' => 'اليونان'],
            ['code' => 'GL', 'english_name' => 'Greenland', 'arabic_name' => 'غرينلاند', 'slug' => 'غرينلاند'],
            ['code' => 'GD', 'english_name' => 'Grenada', 'arabic_name' => 'غرينادا', 'slug' => 'غرينادا'],
            ['code' => 'GP', 'english_name' => 'Guadeloupe', 'arabic_name' => 'غوادلوب', 'slug' => 'غوادلوب'],
            ['code' => 'GU', 'english_name' => 'Guam', 'arabic_name' => 'غوام', 'slug' => 'غوام'],
            ['code' => 'GT', 'english_name' => 'Guatemala', 'arabic_name' => 'غواتيمالا', 'slug' => 'غواتيمالا'],
            ['code' => 'GN', 'english_name' => 'Guinea', 'arabic_name' => 'غينيا', 'slug' => 'غينيا'],
            ['code' => 'GW', 'english_name' => 'Guinea-Bissau', 'arabic_name' => 'غينيا بيساو', 'slug' => 'غينيا-بيساو'],
            ['code' => 'GY', 'english_name' => 'Guyana', 'arabic_name' => 'غيانا', 'slug' => 'غيانا'],
            ['code' => 'HT', 'english_name' => 'Haiti', 'arabic_name' => 'هايتي', 'slug' => 'هايتي'],
            ['code' => 'HM', 'english_name' => 'Heard and Mc Donald Islands', 'arabic_name' => 'هيرد وجزر ماكدونالد', 'slug' => 'هيرد-وجزر-ماكدونالد'],
            ['code' => 'HN', 'english_name' => 'Honduras', 'arabic_name' => 'هندوراس', 'slug' => 'هندوراس'],
            ['code' => 'HK', 'english_name' => 'Hong Kong', 'arabic_name' => 'هونغ كونغ الصينية', 'slug' => 'هونغ-كونغ-الصينية'],
            ['code' => 'HU', 'english_name' => 'Hungary', 'arabic_name' => 'هنغاريا', 'slug' => 'هنغاريا'],
            ['code' => 'IS', 'english_name' => 'Iceland', 'arabic_name' => 'أيسلندا', 'slug' => 'أيسلندا'],
            ['code' => 'IN', 'english_name' => 'India', 'arabic_name' => 'الهند', 'slug' => 'الهند'],
            ['code' => 'ID', 'english_name' => 'Indonesia', 'arabic_name' => 'إندونيسيا', 'slug' => 'إندونيسيا'],
            ['code' => 'IR', 'english_name' => 'Iran (Islamic Republic of)', 'arabic_name' => 'إيران', 'slug' => 'إيران'],
            ['code' => 'IQ', 'english_name' => 'Iraq', 'arabic_name' => 'العراق', 'slug' => 'العراق'],
            ['code' => 'IE', 'english_name' => 'Ireland', 'arabic_name' => 'أيرلندا', 'slug' => 'أيرلندا'],
            ['code' => 'IL', 'english_name' => 'Israel', 'arabic_name' => 'إسرائيل', 'slug' => 'إسرائيل'],
            ['code' => 'IT', 'english_name' => 'Italy', 'arabic_name' => 'إيطاليا', 'slug' => 'إيطاليا'],
            ['code' => 'CI', 'english_name' => 'Ivory Coast', 'arabic_name' => 'ساحل العاج', 'slug' => 'ساحل-العاج'],
            ['code' => 'JM', 'english_name' => 'Jamaica', 'arabic_name' => 'جامايكا', 'slug' => 'جامايكا'],
            ['code' => 'JP', 'english_name' => 'Japan', 'arabic_name' => 'اليابان', 'slug' => 'اليابان'],
            ['code' => 'JO', 'english_name' => 'Jordan', 'arabic_name' => 'الأردن', 'slug' => 'الأردن'],
            ['code' => 'KZ', 'english_name' => 'Kazakhstan', 'arabic_name' => 'كازاخستان', 'slug' => 'كازاخستان'],
            ['code' => 'KE', 'english_name' => 'Kenya', 'arabic_name' => 'كينيا', 'slug' => 'كينيا'],
            ['code' => 'KI', 'english_name' => 'Kiribati', 'arabic_name' => 'كيريباتي', 'slug' => 'كيريباتي'],
            ['code' => 'KP', 'english_name' => 'Korea, Democratic People\'s Republic of', 'arabic_name' => 'كوريا الشمالية', 'slug' => 'كوريا-الشمالية'],
            ['code' => 'KR', 'english_name' => 'Korea, Republic of', 'arabic_name' => 'كوريا الجنوبية', 'slug' => 'كوريا-الجنوبية'],
            ['code' => 'KW', 'english_name' => 'Kuwait', 'arabic_name' => 'الكويت', 'slug' => 'الكويت'],
            ['code' => 'KG', 'english_name' => 'Kyrgyzstan', 'arabic_name' => 'قيرغيزستان', 'slug' => 'قيرغيزستان'],
            ['code' => 'LA', 'english_name' => 'Lao People\'s Democratic Republic', 'arabic_name' => 'لاوس', 'slug' => 'لاوس'],
            ['code' => 'LV', 'english_name' => 'Latvia', 'arabic_name' => 'لاتفيا', 'slug' => 'لاتفيا'],
            ['code' => 'LB', 'english_name' => 'Lebanon', 'arabic_name' => 'لبنان', 'slug' => 'لبنان'],
            ['code' => 'LS', 'english_name' => 'Lesotho', 'arabic_name' => 'ليسوتو', 'slug' => 'ليسوتو'],
            ['code' => 'LR', 'english_name' => 'Liberia', 'arabic_name' => 'ليبيريا', 'slug' => 'ليبيريا'],
            ['code' => 'LY', 'english_name' => 'Libyan Arab Jamahiriya', 'arabic_name' => 'ليبيا', 'slug' => 'ليبيا'],
            ['code' => 'LI', 'english_name' => 'Liechtenstein', 'arabic_name' => 'ليختنشتاين', 'slug' => 'ليختنشتاين'],
            ['code' => 'LT', 'english_name' => 'Lithuania', 'arabic_name' => 'ليتوانيا', 'slug' => 'ليتوانيا'],
            ['code' => 'LU', 'english_name' => 'Luxembourg', 'arabic_name' => 'لوكسمبورغ', 'slug' => 'لوكسمبورغ'],
            ['code' => 'MO', 'english_name' => 'Macau', 'arabic_name' => 'مكاو الصينية (منطقة إدارية خاصة)', 'slug' => 'مكاو-الصينية'],
            ['code' => 'MK', 'english_name' => 'Macedonia', 'arabic_name' => 'مقدونيا', 'slug' => 'مقدونيا'],
            ['code' => 'MG', 'english_name' => 'Madagascar', 'arabic_name' => 'مدغشقر', 'slug' => 'مدغشقر'],
            ['code' => 'MW', 'english_name' => 'Malawi', 'arabic_name' => 'ملاوي', 'slug' => 'ملاوي'],
            ['code' => 'MY', 'english_name' => 'Malaysia', 'arabic_name' => 'ماليزيا', 'slug' => 'ماليزيا'],
            ['code' => 'MV', 'english_name' => 'Maldives', 'arabic_name' => 'جزر المالديف', 'slug' => 'جزر-المالديف'],
            ['code' => 'ML', 'english_name' => 'Mali', 'arabic_name' => 'مالي', 'slug' => 'مالي'],
            ['code' => 'MT', 'english_name' => 'Malta', 'arabic_name' => 'مالطا', 'slug' => 'مالطا'],
            ['code' => 'MH', 'english_name' => 'Marshall Islands', 'arabic_name' => 'جزر مارشال', 'slug' => 'جزر-مارشال'],
            ['code' => 'MQ', 'english_name' => 'Martinique', 'arabic_name' => 'جزر المارتينيك', 'slug' => 'جزر-المارتينيك'],
            ['code' => 'MR', 'english_name' => 'Mauritania', 'arabic_name' => 'موريتانيا', 'slug' => 'موريتانيا'],
            ['code' => 'MU', 'english_name' => 'Mauritius', 'arabic_name' => 'موريشيوس', 'slug' => 'موريشيوس'],
            ['code' => 'TY', 'english_name' => 'Mayotte', 'arabic_name' => 'مايوت', 'slug' => 'مايوت'],
            ['code' => 'MX', 'english_name' => 'Mexico', 'arabic_name' => 'المكسيك', 'slug' => 'المكسيك'],
            ['code' => 'FM', 'english_name' => 'Micronesia, Federated States of', 'arabic_name' => 'ميكرونيزيا', 'slug' => 'ميكرونيزيا'],
            ['code' => 'MD', 'english_name' => 'Moldova, Republic of', 'arabic_name' => 'مولدوفا', 'slug' => 'مولدوفا'],
            ['code' => 'MC', 'english_name' => 'Monaco', 'arabic_name' => 'موناكو', 'slug' => 'موناكو'],
            ['code' => 'MN', 'english_name' => 'Mongolia', 'arabic_name' => 'منغوليا', 'slug' => 'منغوليا'],
            ['code' => 'MS', 'english_name' => 'Montserrat', 'arabic_name' => 'مونتسرات', 'slug' => 'مونتسرات'],
            ['code' => 'MA', 'english_name' => 'Morocco', 'arabic_name' => 'المغرب', 'slug' => 'المغرب'],
            ['code' => 'MZ', 'english_name' => 'Mozambique', 'arabic_name' => 'موزمبيق', 'slug' => 'موزمبيق'],
            ['code' => 'MM', 'english_name' => 'Myanmar', 'arabic_name' => 'ميانمار (بورما)', 'slug' => 'ميانمار-بورما'],
            ['code' => 'NA', 'english_name' => 'Namibia', 'arabic_name' => 'ناميبيا', 'slug' => 'ناميبيا'],
            ['code' => 'NR', 'english_name' => 'Nauru', 'arabic_name' => 'ناورو', 'slug' => 'ناورو'],
            ['code' => 'NP', 'english_name' => 'Nepal', 'arabic_name' => 'نيبال', 'slug' => 'نيبال'],
            ['code' => 'NL', 'english_name' => 'Netherlands', 'arabic_name' => 'هولندا', 'slug' => 'هولندا'],
            ['code' => 'AN', 'english_name' => 'Netherlands Antilles', 'arabic_name' => 'جزر الأنتيل الهولندية', 'slug' => 'جزر-الأنتيل-الهولندية'],
            ['code' => 'NC', 'english_name' => 'New Caledonia', 'arabic_name' => 'كاليدونيا الجديدة', 'slug' => 'كاليدونيا-الجديدة'],
            ['code' => 'NZ', 'english_name' => 'New Zealand', 'arabic_name' => 'نيوزيلندا', 'slug' => 'نيوزيلندا'],
            ['code' => 'NI', 'english_name' => 'Nicaragua', 'arabic_name' => 'نيكاراغوا', 'slug' => 'نيكاراغوا'],
            ['code' => 'NE', 'english_name' => 'Niger', 'arabic_name' => 'النيجر', 'slug' => 'النيجر'],
            ['code' => 'NG', 'english_name' => 'Nigeria', 'arabic_name' => 'نيجيريا', 'slug' => 'نيجيريا'],
            ['code' => 'NU', 'english_name' => 'Niue', 'arabic_name' => 'نيوي', 'slug' => 'نيوي'],
            ['code' => 'NF', 'english_name' => 'Norfork Island', 'arabic_name' => 'جزيرة نورفولك', 'slug' => 'جزيرة-نورفولك'],
            ['code' => 'MP', 'english_name' => 'Northern Mariana Islands', 'arabic_name' => 'جزر ماريانا الشمالية', 'slug' => 'جزر-ماريانا-الشمالية'],
            ['code' => 'NO', 'english_name' => 'Norway', 'arabic_name' => 'النرويج', 'slug' => 'النرويج'],
            ['code' => 'OM', 'english_name' => 'Oman', 'arabic_name' => 'عُمان', 'slug' => 'عمان'],
            ['code' => 'PK', 'english_name' => 'Pakistan', 'arabic_name' => 'باكستان', 'slug' => 'باكستان'],
            ['code' => 'PW', 'english_name' => 'Palau', 'arabic_name' => 'بالاو', 'slug' => 'بالاو'],
            ['code' => 'PA', 'english_name' => 'Panama', 'arabic_name' => 'بنما', 'slug' => 'بنما'],
            ['code' => 'PG', 'english_name' => 'Papua New Guinea', 'arabic_name' => 'بابوا غينيا الجديدة', 'slug' => 'بابوا غينيا الجديدة'],
            ['code' => 'PY', 'english_name' => 'Paraguay', 'arabic_name' => 'باراغواي', 'slug' => 'باراغواي'],
            ['code' => 'PE', 'english_name' => 'Peru', 'arabic_name' => 'بيرو', 'slug' => 'بيرو'],
            ['code' => 'PH', 'english_name' => 'Philippines', 'arabic_name' => 'الفلبين', 'slug' => 'الفلبين'],
            ['code' => 'PN', 'english_name' => 'Pitcairn', 'arabic_name' => 'جزر بيتكيرن', 'slug' => 'جزر بيتكيرن'],
            ['code' => 'PL', 'english_name' => 'Poland', 'arabic_name' => 'بولندا', 'slug' => 'بولندا'],
            ['code' => 'PT', 'english_name' => 'Portugal', 'arabic_name' => 'البرتغال', 'slug' => 'البرتغال'],
            ['code' => 'PR', 'english_name' => 'Puerto Rico', 'arabic_name' => 'بورتوريكو', 'slug' => 'بورتوريكو'],
            ['code' => 'QA', 'english_name' => 'Qatar', 'arabic_name' => 'قطر', 'slug' => 'قطر'],
            ['code' => 'SS', 'english_name' => 'Republic of South Sudan', 'arabic_name' => 'جنوب السودان', 'slug' => 'جنوب-السودان'],
            ['code' => 'RE', 'english_name' => 'Reunion', 'arabic_name' => 'روينيون', 'slug' => 'روينيون'],
            ['code' => 'RO', 'english_name' => 'Romania', 'arabic_name' => 'رومانيا', 'slug' => 'رومانيا'],
            ['code' => 'RU', 'english_name' => 'Russian Federation', 'arabic_name' => 'روسيا', 'slug' => 'روسيا'],
            ['code' => 'RW', 'english_name' => 'Rwanda', 'arabic_name' => 'رواندا', 'slug' => 'رواندا'],
            ['code' => 'KN', 'english_name' => 'Saint Kitts and Nevis', 'arabic_name' => 'سانت كيتس ونيفيس', 'slug' => 'سانت-كيتس-ونيفيس'],
            ['code' => 'LC', 'english_name' => 'Saint Lucia', 'arabic_name' => 'سانت لوسيا', 'slug' => 'سانت-لوسيا'],
            ['code' => 'VC', 'english_name' => 'Saint Vincent and the Grenadines', 'arabic_name' => 'سانت فنسنت وجزر غرينادين', 'slug' => 'سانت-فنسنت-وجزر-غرينادين'],
            ['code' => 'WS', 'english_name' => 'Samoa', 'arabic_name' => 'ساموا', 'slug' => 'ساموا'],
            ['code' => 'SM', 'english_name' => 'San Marino', 'arabic_name' => 'سان مارينو', 'slug' => 'سان=مارينو'],
            ['code' => 'ST', 'english_name' => 'Sao Tome and Principe', 'arabic_name' => 'ساو تومي وبرينسيبي', 'slug' => 'ساو-تومي-وبرينسيبي'],
            ['code' => 'SA', 'english_name' => 'Saudi Arabia', 'arabic_name' => 'المملكة العربية السعودية', 'slug' => 'المملكة-العربية-السعودية'],
            ['code' => 'SN', 'english_name' => 'Senegal', 'arabic_name' => 'السنغال', 'slug' => 'السنغال'],
            ['code' => 'RS', 'english_name' => 'Serbia', 'arabic_name' => 'صربيا', 'slug' => 'صربيا'],
            ['code' => 'SC', 'english_name' => 'Seychelles', 'arabic_name' => 'سيشل', 'slug' => 'سيشل'],
            ['code' => 'SL', 'english_name' => 'Sierra Leone', 'arabic_name' => 'سيراليون', 'slug' => 'سيراليون'],
            ['code' => 'SG', 'english_name' => 'Singapore', 'arabic_name' => 'سنغافورة', 'slug' => 'سنغافورة'],
            ['code' => 'SK', 'english_name' => 'Slovakia', 'arabic_name' => 'سلوفاكيا', 'slug' => 'سلوفاكيا'],
            ['code' => 'SI', 'english_name' => 'Slovenia', 'arabic_name' => 'سلوفينيا', 'slug' => 'سلوفينيا'],
            ['code' => 'SB', 'english_name' => 'Solomon Islands', 'arabic_name' => 'جزر سليمان', 'slug' => 'جزر-سليمان'],
            ['code' => 'SO', 'english_name' => 'Somalia', 'arabic_name' => 'الصومال', 'slug' => 'الصومال'],
            ['code' => 'ZA', 'english_name' => 'South Africa', 'arabic_name' => 'جنوب أفريقيا', 'slug' => 'جنوب-أفريقيا'],
            ['code' => 'GS', 'english_name' => 'South Georgia South Sandwich Islands', 'arabic_name' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'slug' => 'جورجيا-الجنوبية-وجزر-ساندويتش-الجنوبية'],
            ['code' => 'ES', 'english_name' => 'Spain', 'arabic_name' => 'إسبانيا', 'slug' => 'إسبانيا'],
            ['code' => 'LK', 'english_name' => 'Sri Lanka', 'arabic_name' => 'سريلانكا', 'slug' => 'سريلانكا'],
            ['code' => 'SH', 'english_name' => 'St. Helena', 'arabic_name' => 'سانت هيلانة', 'slug' => 'سانت-هيلانة'],
            ['code' => 'PM', 'english_name' => 'St. Pierre and Miquelon', 'arabic_name' => 'سانت بيير وميكولون', 'slug' => 'سانت-بيير-وميكولون'],
            ['code' => 'SD', 'english_name' => 'Sudan', 'arabic_name' => 'السودان', 'slug' => 'السودان'],
            ['code' => 'SR', 'english_name' => 'Suriname', 'arabic_name' => 'سورينام', 'slug' => 'سورينام'],
            ['code' => 'SJ', 'english_name' => 'Svalbarn and Jan Mayen Islands', 'arabic_name' => 'سفالبارد وجان مايان', 'slug' => 'سفالبارد-وجان-مايان'],
            ['code' => 'SZ', 'english_name' => 'Swaziland', 'arabic_name' => 'سوازيلاند', 'slug' => 'سوازيلاند'],
            ['code' => 'SE', 'english_name' => 'Sweden', 'arabic_name' => 'السويد', 'slug' => 'السويد'],
            ['code' => 'CH', 'english_name' => 'Switzerland', 'arabic_name' => 'سويسرا', 'slug' => 'سويسرا'],
            ['code' => 'SY', 'english_name' => 'Syrian Arab Republic', 'arabic_name' => 'سوريا', 'slug' => 'سوريا'],
            ['code' => 'TW', 'english_name' => 'Taiwan', 'arabic_name' => 'تايوان', 'slug' => 'تايوان'],
            ['code' => 'TJ', 'english_name' => 'Tajikistan', 'arabic_name' => 'طاجيكستان', 'slug' => 'طاجيكستان'],
            ['code' => 'TZ', 'english_name' => 'Tanzania, United Republic of', 'arabic_name' => 'تنزانيا', 'slug' => 'تنزانيا'],
            ['code' => 'TH', 'english_name' => 'Thailand', 'arabic_name' => 'تايلاند', 'slug' => 'تايلاند'],
            ['code' => 'TG', 'english_name' => 'Togo', 'arabic_name' => 'توغو', 'slug' => 'توغو'],
            ['code' => 'TK', 'english_name' => 'Tokelau', 'arabic_name' => 'توكيلو', 'slug' => 'توكيلو'],
            ['code' => 'TO', 'english_name' => 'Tonga', 'arabic_name' => 'تونغا', 'slug' => 'تونغا'],
            ['code' => 'TT', 'english_name' => 'Trinidad and Tobago', 'arabic_name' => 'ترينيداد وتوباغو', 'slug' => 'ترينيداد-وتوباغو'],
            ['code' => 'TN', 'english_name' => 'Tunisia', 'arabic_name' => 'تونس', 'slug' => 'تونس'],
            ['code' => 'TR', 'english_name' => 'Turkey', 'arabic_name' => 'تركيا', 'slug' => 'تركيا'],
            ['code' => 'TM', 'english_name' => 'Turkmenistan', 'arabic_name' => 'تركمانستان', 'slug' => 'تركمانستان'],
            ['code' => 'TC', 'english_name' => 'Turks and Caicos Islands', 'arabic_name' => 'جزر توركس وكايكوس', 'slug' => 'جزر-توركس-وكايكوس'],
            ['code' => 'TV', 'english_name' => 'Tuvalu', 'arabic_name' => 'توفالو', 'slug' => 'توفالو'],
            ['code' => 'UG', 'english_name' => 'Uganda', 'arabic_name' => 'أوغندا', 'slug' => 'أوغندا'],
            ['code' => 'UA', 'english_name' => 'Ukraine', 'arabic_name' => 'أوكرانيا', 'slug' => 'أوكرانيا'],
            ['code' => 'AE', 'english_name' => 'United Arab Emirates', 'arabic_name' => 'الإمارات العربية المتحدة', 'slug' => 'الإمارات-العربية-المتحدة'],
            ['code' => 'GB', 'english_name' => 'United Kingdom', 'arabic_name' => 'المملكة المتحدة', 'slug' => 'المملكة-المتحدة'],
            ['code' => 'UM', 'english_name' => 'United States minor outlying islands', 'arabic_name' => 'جزر الولايات المتحدة النائية', 'slug' => 'جزر-الولايات-المتحدة-النائية'],
            ['code' => 'UY', 'english_name' => 'Uruguay', 'arabic_name' => 'أورغواي', 'slug' => 'أورغواي'],
            ['code' => 'UZ', 'english_name' => 'Uzbekistan', 'arabic_name' => 'أوزبكستان', 'slug' => 'أوزبكستان'],
            ['code' => 'VU', 'english_name' => 'Vanuatu', 'arabic_name' => 'فانواتو', 'slug' => 'فانواتو'],
            ['code' => 'VA', 'english_name' => 'Vatican City State', 'arabic_name' => 'الفاتيكان', 'slug' => 'الفاتيكان'],
            ['code' => 'VE', 'english_name' => 'Venezuela', 'arabic_name' => 'فنزويلا', 'slug' => 'فنزويلا'],
            ['code' => 'VN', 'english_name' => 'Vietnam', 'arabic_name' => 'فيتنام', 'slug' => 'فيتنام'],
            ['code' => 'VG', 'english_name' => 'Virgin Islands (British)', 'arabic_name' => 'جزر فيرجن البريطانية', 'slug' => 'جزر-فيرجن-البريطانية'],
            ['code' => 'VI', 'english_name' => 'Virgin Islands (U.S.)', 'arabic_name' => 'جزر فيرجن التابعة للولايات المتحدة', 'slug' => 'جزر-فيرجن-التابعة-للولايات-المتحدة'],
            ['code' => 'WF', 'english_name' => 'Wallis and Futuna Islands', 'arabic_name' => 'جزر والس وفوتونا', 'slug' => 'جزر-والس-وفوتونا'],
            ['code' => 'EH', 'english_name' => 'Western Sahara', 'arabic_name' => 'الصحراء الغربية', 'slug' => 'الصحراء-الغربية'],
            ['code' => 'YE', 'english_name' => 'Yemen', 'arabic_name' => 'اليمن', 'slug' => 'اليمن'],
            ['code' => 'YU', 'english_name' => 'Yugoslavia', 'arabic_name' => 'يوغوسلافيا', 'slug' => 'يوغوسلافيا'],
            ['code' => 'ZR', 'english_name' => 'Zaire', 'arabic_name' => 'زائير', 'slug' => 'زائير'],
            ['code' => 'ZM', 'english_name' => 'Zambia', 'arabic_name' => 'زامبيا', 'slug' => 'زامبيا'],
            ['code' => 'ZW', 'english_name' => 'Zimbabwe', 'arabic_name' => 'زيمبابوي', 'slug' => 'زيمبابوي'],
        ];

        foreach ($countries as $country) {
            \App\Models\Country::create([
                'code'  => $country['code'],
                'title' => [
                    'ar' => $country['arabic_name'],
                    'en' => $country['english_name'],
                ],
                'slug' => $country['slug'],
            ]);
            //dump($country);
        }
//        DB::table('countries')->insert($countriess);
    }
}
